<?php

namespace Blogger\BlogBundle\Repository;

/**
 * TeOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeOneRepository extends \Doctrine\ORM\EntityRepository
{
}
