<?php

namespace Blogger\BlogBundle\Repository;

/**
 * TeTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeTwoRepository extends \Doctrine\ORM\EntityRepository
{
}
