# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    app.token_authenticator:
            class: Blogger\BlogBundle\Security\TokenAuthenticator
    api_key_provider:
        class: Blogger\BlogBundle\Security\User\WebserviceUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]
#    api_key_user_provider:
#        class: Blogger\BlogBundle\Security\ApiKeyUserProvider

parameters:
    #parameter_name: value

#services:
#    admin.blog:
#            class: Blogger\BlogBundle\Admin\BlogAdmin
#            arguments: [~, Blogger\BlogBundle\Entity\Blog, ~]
#            tags:
#                - { name: sonata.admin, manager_type: orm, label: Blog }
#
#    admin.comment:
#                class: Blogger\BlogBundle\Admin\CommentAdmin
#                arguments: [~, Blogger\BlogBundle\Entity\Comment, ~]
#                tags:
#                    - { name: sonata.admin, manager_type: orm, label: Comment }
