# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

#services:
#    admin.blog:
#            class: Blogger\BlogBundle\Admin\BlogAdmin
#            arguments: [~, Blogger\BlogBundle\Entity\Blog, ~]
#            tags:
#                - { name: sonata.admin, manager_type: orm, label: Blog }
#
#    admin.comment:
#                class: Blogger\BlogBundle\Admin\CommentAdmin
#                arguments: [~, Blogger\BlogBundle\Entity\Comment, ~]
#                tags:
#                    - { name: sonata.admin, manager_type: orm, label: Comment }
